model: SA_EEND
train_audio_dir: YOUR_PATH
train_audio_annotation_dir: YOUR_PATH
val_audio_dir: YOUR_PATH
val_annotation_dir: YOUR_PATH
test_audio_dir: YOUR_PATH
test_annotation_dir: YOUR_PATH
train_speakers: null
val_speakers: null
test_speakers: null
input_transform: logmel23_mn
n_speakers: 2
chunk_size: 500
context_size: 7
subsampling: 10
win_length: 400
hop_length: 160
lr: noam
base_lr: 1
warmup_steps: 100000
input_dim: 345
d_model: 256
nhead: 4
dim_ffn: 2048
num_layers: 4
seed: 42
ckpt_dir: YOUR_PATH
device: cuda:0
max_epochs: 100
gradient_clip_val: 1